package server;


import java.awt.Color;
import java.awt.Component;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.FontFormatException;
import java.awt.Rectangle;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
import javax.swing.BoxLayout;
import javax.swing.JButton;
import javax.swing.JScrollPane;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.LinkedHashMap;
import java.util.List;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.ScrollPaneConstants;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.nio.file.StandardCopyOption;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author taioli Francesco rappresenta la classe per inviare , ricevere i
 * messaggi
 */
public class ChatGUi extends javax.swing.JFrame {

    /**
     * Creates new form IndixisGui
     */
    public ChatGUi(String username, String password) {
        this.username = username;
        this.password = password;
        initComponents();
        registrazione(username, password);
        inizialize();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        title = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        addFriend = new javax.swing.JButton();
        removeFriends = new javax.swing.JButton();
        friendRequestList = new javax.swing.JButton();
        numberOfRequest = new javax.swing.JLabel();
        menu = new javax.swing.JPanel();
        jSeparator2 = new javax.swing.JSeparator();
        friend = new javax.swing.JPanel();
        tab = new javax.swing.JTabbedPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        messageText = new javax.swing.JTextPane();
        inviaTesto = new javax.swing.JButton();
        inviaFoto = new javax.swing.JButton();
        indixis = new javax.swing.JLabel();
        inviaFile = new javax.swing.JButton();
        inviaAudio = new javax.swing.JButton();
        user = new javax.swing.JLabel();
        information = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(100, 181, 246));

        title.setBackground(new java.awt.Color(100, 181, 246));

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        addFriend.setIcon(new javax.swing.ImageIcon(getClass().getResource("/indixis/img/add.png"))); // NOI18N
        addFriend.setText("Add");
        addFriend.setBorder(null);
        addFriend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addFriendActionPerformed(evt);
            }
        });

        removeFriends.setIcon(new javax.swing.ImageIcon(getClass().getResource("/indixis/img/remove.png"))); // NOI18N
        removeFriends.setText("Remove");
        removeFriends.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeFriendsActionPerformed(evt);
            }
        });

        friendRequestList.setIcon(new javax.swing.ImageIcon(getClass().getResource("/indixis/img/request.png"))); // NOI18N
        friendRequestList.setText("View request");
        friendRequestList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                friendRequestListActionPerformed(evt);
            }
        });

        numberOfRequest.setBackground(new java.awt.Color(0, 0, 255));
        numberOfRequest.setForeground(new java.awt.Color(0, 51, 51));
        numberOfRequest.setText("0");

        javax.swing.GroupLayout titleLayout = new javax.swing.GroupLayout(title);
        title.setLayout(titleLayout);
        titleLayout.setHorizontalGroup(
            titleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(titleLayout.createSequentialGroup()
                .addGap(600, 600, 600)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(titleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(removeFriends)
                    .addGroup(titleLayout.createSequentialGroup()
                        .addComponent(addFriend, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(friendRequestList)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(numberOfRequest, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(26, 26, 26))
        );
        titleLayout.setVerticalGroup(
            titleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(titleLayout.createSequentialGroup()
                .addGroup(titleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(titleLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(friendRequestList, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(numberOfRequest)
                    .addComponent(addFriend, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(removeFriends, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 9, Short.MAX_VALUE))
        );

        menu.setBackground(new java.awt.Color(100, 181, 246));

        javax.swing.GroupLayout menuLayout = new javax.swing.GroupLayout(menu);
        menu.setLayout(menuLayout);
        menuLayout.setHorizontalGroup(
            menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 13, Short.MAX_VALUE)
        );
        menuLayout.setVerticalGroup(
            menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, menuLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        friend.setBackground(new java.awt.Color(227, 242, 253));

        javax.swing.GroupLayout friendLayout = new javax.swing.GroupLayout(friend);
        friend.setLayout(friendLayout);
        friendLayout.setHorizontalGroup(
            friendLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 156, Short.MAX_VALUE)
        );
        friendLayout.setVerticalGroup(
            friendLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 43, Short.MAX_VALUE)
        );

        tab.setBackground(new java.awt.Color(255, 255, 255));
        tab.setForeground(new java.awt.Color(0, 153, 102));
        tab.setTabLayoutPolicy(javax.swing.JTabbedPane.SCROLL_TAB_LAYOUT);
        tab.setAutoscrolls(true);
        tab.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tab.setInheritsPopupMenu(true);
        tab.setMaximumSize(new java.awt.Dimension(600, 600));
        tab.setMinimumSize(new java.awt.Dimension(500, 600));

        messageText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                messageTextKeyReleased(evt);
            }
        });
        jScrollPane2.setViewportView(messageText);

        inviaTesto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/indixis/img/telegram-logo.png"))); // NOI18N
        inviaTesto.setMaximumSize(new java.awt.Dimension(205, 137));
        inviaTesto.setMinimumSize(new java.awt.Dimension(205, 137));
        inviaTesto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                inviaTestoMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                inviaTestoMouseReleased(evt);
            }
        });
        inviaTesto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inviaTestoActionPerformed(evt);
            }
        });
        inviaTesto.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                inviaTestoPropertyChange(evt);
            }
        });
        inviaTesto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                inviaTestoKeyReleased(evt);
            }
        });

        inviaFoto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/indixis/img/image.png"))); // NOI18N
        inviaFoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inviaFotoActionPerformed(evt);
            }
        });

        indixis.setText("INDIXIS");

        inviaFile.setIcon(new javax.swing.ImageIcon(getClass().getResource("/indixis/img/attachment.png"))); // NOI18N
        inviaFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inviaFileActionPerformed(evt);
            }
        });

        inviaAudio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/indixis/img/microphone.png"))); // NOI18N
        inviaAudio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inviaAudioActionPerformed(evt);
            }
        });

        user.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 24)); // NOI18N

        information.setText("Your list of friends");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(180, 180, 180)
                        .addComponent(menu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(friend, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 356, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(inviaTesto, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(inviaAudio, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(tab, javax.swing.GroupLayout.PREFERRED_SIZE, 475, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(inviaFile, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(inviaFoto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(157, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(indixis, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(user, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(information, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(title, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(user, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(indixis, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addComponent(information, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(friend, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(menu, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(43, 43, 43))
                        .addComponent(tab, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 389, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(inviaFile)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(inviaFoto)))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(inviaTesto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(inviaAudio)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40))))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(title, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 544, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void inviaTestoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inviaTestoActionPerformed
        String text = messageText.getText();
        ChatPaneMsgBox paneRight = new ChatPaneMsgBox(lenControl(text), true, TypeMessage.MESSAGGIO);
        addPanel(paneRight);

        messageText.setText("");;

        String localUser = user.getText();
        String destinatario = tab.getTitleAt(0);
        Calendar now = Calendar.getInstance();
        int day = now.get(Calendar.DAY_OF_MONTH);
        int hour = now.get(Calendar.HOUR_OF_DAY);
        Message message = new Message(localUser, text, destinatario, hour, day, TypeMessage.MESSAGGIO, false);
        addMessage(message);
        Connection.inviaMessaggio(text, destinatario);
    }//GEN-LAST:event_inviaTestoActionPerformed

    private void inviaFotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inviaFotoActionPerformed
        String localUser = user.getText();
        String destinatario = tab.getTitleAt(0);
        Calendar now = Calendar.getInstance();
        int day = now.get(Calendar.DAY_OF_MONTH);
        int hour = now.get(Calendar.HOUR_OF_DAY);
        JFileChooser filechooser = new JFileChooser();
        
        int returnValue = filechooser.showOpenDialog(null); //del parent maggiore
        if (returnValue == filechooser.APPROVE_OPTION) {
        
            
        Path from = Paths.get(filechooser.getSelectedFile().getAbsolutePath());
        Path dest = Paths.get(Connection.pathSendImage+filechooser.getSelectedFile().getName());
        System.out.println("dest"+dest);
        System.out.println("from"+from);
        
            try {
                Files.copy(from,dest,StandardCopyOption.REPLACE_EXISTING);
            } catch (IOException ex) {
                Logger.getLogger(ChatGUi.class.getName()).log(Level.SEVERE, null, ex);
            }
       
        ChatPaneMsgBox paneLeft = new ChatPaneMsgBox(dest.toString(), true, TypeMessage.FOTO);
        addPanel(paneLeft);
        
        Connection.invioFile(dest.toString(),destinatario, TypeMessage.FOTO);
        connection.insertFile(filechooser.getSelectedFile().getAbsolutePath(), tab.getTitleAt(0), TypeMessage.FOTO);
        }
    }//GEN-LAST:event_inviaFotoActionPerformed

    private void inviaTestoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_inviaTestoMousePressed
        if (evt.getClickCount() == 1) {
            System.out.println(evt.getClass());
        }
    }//GEN-LAST:event_inviaTestoMousePressed

    private void inviaTestoMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_inviaTestoMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_inviaTestoMouseReleased

    private void inviaTestoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_inviaTestoKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_inviaTestoKeyReleased

    private void inviaTestoPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_inviaTestoPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_inviaTestoPropertyChange

    private void messageTextKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_messageTextKeyReleased
        if (messageText.getText().equals("")) {
            inviaTesto.setText("Registra");
            inviaTesto.revalidate();
            inviaTesto.repaint();
        } else {
            inviaTesto.setText("Invia");
            inviaTesto.revalidate();
            inviaTesto.repaint();
        }
    }//GEN-LAST:event_messageTextKeyReleased

    private void inviaFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inviaFileActionPerformed
        JFileChooser filechooser = new JFileChooser();
        int returnValue = filechooser.showOpenDialog(null); //del parent maggiore
        if (returnValue == filechooser.APPROVE_OPTION) {
            System.out.println(filechooser.getSelectedFile().getAbsolutePath());;
            Connection.invioFile(filechooser.getSelectedFile().getAbsolutePath(), tab.getTitleAt(0), TypeMessage.FILE);
            connection.insertFile(filechooser.getSelectedFile().getAbsolutePath(), tab.getTitleAt(0), TypeMessage.FILE);
        }
    }//GEN-LAST:event_inviaFileActionPerformed

    private void inviaAudioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inviaAudioActionPerformed
        JFileChooser filechooser = new JFileChooser();
        int returnValue = filechooser.showOpenDialog(null); //del parent maggiore
        if (returnValue == filechooser.APPROVE_OPTION) {
            System.out.println(filechooser.getSelectedFile().getAbsolutePath());;
            Connection.invioFile(filechooser.getSelectedFile().getAbsolutePath(), tab.getTitleAt(0), TypeMessage.AUDIO);
        }
    }//GEN-LAST:event_inviaAudioActionPerformed

    private void friendRequestListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_friendRequestListActionPerformed

        if (Ricezione.friendsListWithoutAnswer.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Non sono presenti richieste di amicizia");
        } else {
            new RichiesteDiAmicizia();
        }
    }//GEN-LAST:event_friendRequestListActionPerformed

    private void removeFriendsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeFriendsActionPerformed
        new RemoveFriend(this);
    }//GEN-LAST:event_removeFriendsActionPerformed

    private void addFriendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addFriendActionPerformed
        new AddFriend(this);
    }//GEN-LAST:event_addFriendActionPerformed

    /**
     * setta il nome dell'utente nella barra titolo
     *
     * @param userName
     */
    public void setUser(String userName) {
        user.setText("Bentornato, " + userName);
    }

    /**
     * aggiunge un messaggio al array
     *
     * @param messaggio
     */
    public void addMessage(Message messaggio) {

        //startSound("/indixis/sound/soundMessage.mp3");
        listaMessaggi.add(messaggio);
        try {
            setMessage();
        } catch (IOException ex) {
            Logger.getLogger(ChatGUi.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * modifica il label di notifica di un utente
     *
     * @param user
     */
    public void addNotify(String user) {
        if(!user.equals(tab.getTitleAt(0))){
        JLabel k = new JLabel();
        int i = Integer.valueOf((String) notifiche.get(user));
        k = (JLabel) (counterNotifiche.get(i));
        String numberOfCurrentNotify = k.getText();
        String text = String.valueOf(Integer.parseInt(numberOfCurrentNotify) + 1);
        k.setText(text);
        }
    }

    private boolean registrazione(String username, String password) {
        MessageDigest md;

        try {
            md = MessageDigest.getInstance("MD5");
            byte[] passBytes = password.getBytes();
            md.reset();
            StringBuilder sb = new StringBuilder();
            for (int i = 0; i < passBytes.length; i++) {
                sb.append(Integer.toHexString(0xff & passBytes[i]));
            }
            password = sb.toString();
        } catch (NoSuchAlgorithmException ex) {
            System.out.println("Errore creazione hash password");
        }

        connection = new Connection(5555, "127.0.0.1", username, password, "login", this);

        return true;
    }

    /**
     *
     * @param listaAmici
     */
    public void setFriendsListArray(ArrayList<String> listaAmici) {
        friend.removeAll();
        ar = listaAmici;
        amici();

        friend.setLayout(new BoxLayout(friend, BoxLayout.Y_AXIS));
        friend.setVisible(true);
        friend.revalidate();
        friend.repaint();
    }

    /**
     * setta gli amici, aggiunge i l abel delle notifche
     */
    public void amici() {
        int x = 0;
        for (int i = 0; i < ar.size(); i++) {
            String text = (String) ar.get(i).toString();

            //notifiche
            notifiche.put(text, String.valueOf(i));
            JLabel notify = new JLabel("0");
//            notify.set
            counterNotifiche.add(notify);

            JButton button = new JButton((String) ar.get(i).toString());

            button.addActionListener(new ActionListener() {
                public void actionPerformed(ActionEvent ae) {
                    notify.setText("0");
                    //panelMessage.setBackground(Color.LIGHT_GRAY);
                    arrayTab.add(tab);
                    if (x == 0) {
                        tab.addTab(text, scroll);

                    } else {
                        int index = tab.getSelectedIndex();
                        tab.setTitleAt(0, text);
                    }
                    try {
                        setMessage();
                    } catch (IOException ex) {
                        Logger.getLogger(ChatGUi.class.getName()).log(Level.SEVERE, null, ex);
                    }
                    System.out.println("--------------------------------------------");
                }
            });
            JPanel p = new JPanel();
            p.setBackground(Color.red);
            p.setMaximumSize(new Dimension(200, 30));
            p.add(button);
            p.add(notify);
            friend.add(p);
            System.out.println((String) ar.get(i).toString());
        }
    }

    public void riceviAmicizia(String username) {
        setNumberOfRequest();
        //startSound("request.wav");
        JOptionPane.showMessageDialog(null, "Hai ricevuto una richiesta d'amicizia da " + username + "vai nell'apposita sezione per accettare");
    }

    public void nuovoAmico(String username) {
        JOptionPane.showMessageDialog(null, username + " è un tuo nuovo amico ! Ora puoi chattarci !!!");
    }

    public void rimozioneAmico(String username) {
        JOptionPane.showMessageDialog(null, username + " non è più tuo amico :(");
    }

    /**
     * setta i messagi nel panel in corrispondenza dell utente
     */
    public void setMessage() throws FileNotFoundException, IOException {
        String destinatario = tab.getTitleAt(0);
        panelMessage.removeAll();
        //add your elements
        panelMessage.revalidate();
        panelMessage.repaint();
        ChatPaneMsgBox defaultMessage = new ChatPaneMsgBox("Benvenuto in Indixis! inizia a chattare!", true, TypeMessage.MESSAGGIO);
        addPanel(defaultMessage);
        ChatPaneMsgBox defaultMessage2 = new ChatPaneMsgBox("Scrivi subito ai tuoi amici!", false, TypeMessage.MESSAGGIO);
        addPanel(defaultMessage2);

        
        
        for (int i = 0; i < listaMessaggi.size(); i++) {
        
             if (listaMessaggi.get(i).getDestinatario().equals(destinatario) || listaMessaggi.get(i).getUser().equals(destinatario)) {
            System.out.println(listaMessaggi.get(i).toString());

            Message mex = listaMessaggi.get(i);
            String pathOrText = "";
            if (mex.getType() == TypeMessage.AUDIO || mex.getType() == TypeMessage.FILE || mex.getType() == TypeMessage.FOTO) {
                pathOrText = Ricezione.pathFileReceived + listaMessaggi.get(i).getFilename();
            } else {
                pathOrText = mex.getMessage();
            }

            ChatPaneMsgBox paneLeft = new ChatPaneMsgBox(pathOrText, mex.isForeign(), mex.getType());
            addPanel(paneLeft);
            }
        }
        
         Rectangle rect = panelMessage.getBounds();
                Rectangle r2 = scroll.getViewport().getVisibleRect();
                panelMessage.scrollRectToVisible(new Rectangle((int) rect.getWidth(), 
                        (int) rect.getHeight(), (int) r2.getWidth(), (int) r2.getHeight()));
    }

    /**
     * aggiunge un pboxPanel al pannello dei messaggi
     *
     * @param panel
     */
    private void addPanel(Component panel) {
        panelMessage.add(panel);
        panelMessage.revalidate();
        panelMessage.repaint();
    }

 

    /**
     * controlla la lughezza del messaggio, se > di 44 va a capo
     *
     * @param message
     * @return
     */
    private String lenControl(String message) {

        String newMessage = "<html>";
        String[] splitMessage;
        if (message.length() > 44) {
            splitMessage = message.split(" ");
            for (int i = 0; i < splitMessage.length - 1; i++) {
                if (i == 1) {
                    newMessage += splitMessage[i];
                } else {
                    newMessage += " " + splitMessage[i];
                }
            }
            System.out.println("################################PRIMAAA#" + " " + newMessage);
            newMessage += "<br>" + splitMessage[splitMessage.length - 1] + "</html>";

        }
        System.out.println("##############################################" + " " + newMessage);
        return newMessage;
    }

    /**
     * fa partire un suono che avvisa l'arrivo di un messaggio
     *
     * @param sound
     */
//    private void startSound(String sound) {
//        try {
//            AudioInputStream audioIn = AudioSystem.getAudioInputStream(ChatGUi.class.getResource(sound));
//            Clip clip = AudioSystem.getClip();
//            clip.open(audioIn);
//            clip.start();
//        } catch (Exception ex) {
//            Logger.getLogger(ChatGUi.class.getName()).log(Level.SEVERE, null, ex);
//        }
//
//    }

    /**
     * setta i bottoni circolari
     */
    private void setCircolar() {
        addFriend.setBorder(new RoundedBorder(10));
        removeFriends.setBorder(new RoundedBorder(10));
        friendRequestList.setBorder(new RoundedBorder(10));
         inviaFile.setBorder(new RoundedBorder(10));
         inviaFoto.setBorder(new RoundedBorder(10));
         inviaTesto.setBorder(new RoundedBorder(10));
        inviaAudio.setBorder(new RoundedBorder(10));
    }

    private void setFont() {
        try {
            Font font = Font.createFont(Font.TRUETYPE_FONT, getClass().getResourceAsStream("Roboto-thin.ttf"));
            indixis.setFont(font.deriveFont(Font.BOLD, 48f));
            information.setFont(font.deriveFont(Font.BOLD, 22f));
           
        } catch (FontFormatException ex) {
            Logger.getLogger(ChatGUi.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(ChatGUi.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    public void inizialize() {
        panelMessage = new JPanel();
        //panelMessage.setBackground(Color.LIGHT_GRAY);
        setCircolar();
        setFont();
             friend.setBackground(new java.awt.Color(227, 242, 253));
        System.out.println("################################################aggiutno");
        panelMessage.setLayout(new BoxLayout(panelMessage, BoxLayout.Y_AXIS));
        //panelMessage.setLayout(new BoxLayout(panelMessage, BoxLayout.Y_AXIS));
        //scroll.add(panelMessage);
        //panelMessage.setSize(new Dimension(500,500));
        //panelMessage.setBackground(Color.pink);
        //panelMessage.setMaximumSize(new Dimension(600, 600));
        scroll.setViewportView(panelMessage);
        //scroll.setPreferredSize(new Dimension(50, 50));
        //scroll.getVerticalScrollBar().setUI(new MyScrollBarUI());

    }

    /**
     * setta il numero delle richieste di amicizia
     */
    public void setNumberOfRequest() {
        numberOfRequest.setText(String.valueOf(Ricezione.friendsListWithoutAnswer.size()));

    }

    public void setListaMessaggi(ArrayList messaggi) {
        listaMessaggi = messaggi;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addFriend;
    private javax.swing.JPanel friend;
    private javax.swing.JButton friendRequestList;
    private javax.swing.JLabel indixis;
    private javax.swing.JLabel information;
    private javax.swing.JButton inviaAudio;
    private javax.swing.JButton inviaFile;
    private javax.swing.JButton inviaFoto;
    private javax.swing.JButton inviaTesto;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JPanel menu;
    private javax.swing.JTextPane messageText;
    private javax.swing.JLabel numberOfRequest;
    private javax.swing.JButton removeFriends;
    private javax.swing.JTabbedPane tab;
    private javax.swing.JPanel title;
    public javax.swing.JLabel user;
    // End of variables declaration//GEN-END:variables
    public static ArrayList ar = new ArrayList();
    public ArrayList arrayTab = new ArrayList();
    private String username;
    private String password;
    private Connection connection;
    private JPanel panelMessage;
    int v = ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS;
    int h = ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS;
    JScrollPane scroll = new JScrollPane(v, h);
    private List<Message> listaMessaggi = new ArrayList();
    LinkedHashMap notifiche = new LinkedHashMap();
    private List<JLabel> counterNotifiche = new ArrayList();
}
